"""
Explanation generator for ML alerts
"""

from typing import Dict, Any, List, Optional
import logging
from datetime import datetime

from .feature_mapper import FeatureMapper

logger = logging.getLogger(__name__)


class ExplanationGenerator:
    """
    Generates human-readable explanations for ML alerts
    
    Attributes:
        feature_mapper (FeatureMapper): Maps features to descriptions
        max_features (int): Maximum number of features to include
    """
    
    def __init__(self, max_features: int = 5):
        """
        Initialize the explanation generator.
        
        Args:
            max_features (int): Maximum number of features to include
        """
        self.feature_mapper = FeatureMapper()
        self.max_features = max_features
        logger.info(f"ExplanationGenerator initialized with max_features={max_features}")
    
    def generate_explanation(self, 
                           alert_data: Dict[str, Any],
                           feature_importances: Optional[Dict[str, float]] = None) -> str:
        """
        Generate a human-readable explanation for an alert
        
        Args:
            alert_data (Dict): Alert data including:
                - attack_type (str): Type of attack
                - source_ip (str): Source IP
                - dest_ip (str): Destination IP
                - message (str): Alert message
                - ml_confidence (float): ML confidence
            feature_importances (Dict[str, float], optional): Feature importance scores
            
        Returns:
            str: Human-readable explanation
        """
        attack_type = alert_data.get('attack_type', 'unknown')
        source_ip = alert_data.get('source_ip', 'unknown')
        dest_ip = alert_data.get('dest_ip', 'unknown')
        confidence = alert_data.get('ml_confidence', 0.5)
        
        # Get attack pattern
        pattern = self.feature_mapper.get_attack_pattern_explanation(attack_type)
        
        # Build explanation parts
        parts = []
        
        # 1. Introduction
        intro = f"Alert: {pattern.get('description', attack_type)} detected"
        parts.append(intro)
        
        # 2. Source and destination
        parts.append(f"Source: {source_ip} → Destination: {dest_ip}")
        
        # 3. Confidence
        confidence_text = self._get_confidence_text(confidence)
        parts.append(f"Confidence: {confidence_text}")
        
        # 4. Feature importance (if provided)
        if feature_importances:
            importance_text = self._get_importance_text(feature_importances)
            if importance_text:
                parts.append(f"Key indicators: {importance_text}")
        
        # 5. Attack pattern explanation
        explanation = pattern.get('explanation', '')
        if explanation:
            parts.append(f"Pattern: {explanation}")
        
        # 6. Summary
        parts.append("This alert was generated by the machine learning model based on network traffic patterns.")
        
        return " ".join(parts)
    
    def generate_detailed_explanation(self,
                                    alert_data: Dict[str, Any],
                                    feature_importances: Optional[Dict[str, float]] = None,
                                    top_k: int = 5) -> Dict[str, Any]:
        """
        Generate a detailed structured explanation
        
        Args:
            alert_data (Dict): Alert data
            feature_importances (Dict[str, float], optional): Feature importance scores
            top_k (int): Number of top features to include
            
        Returns:
            Dict: Structured explanation
        """
        attack_type = alert_data.get('attack_type', 'unknown')
        confidence = alert_data.get('ml_confidence', 0.5)
        
        # Get attack pattern
        pattern = self.feature_mapper.get_attack_pattern_explanation(attack_type)
        
        # Build structured explanation
        explanation = {
            'timestamp': datetime.utcnow().isoformat(),
            'attack_type': attack_type,
            'description': pattern.get('description', 'Unknown attack'),
            'confidence': confidence,
            'confidence_level': self._get_confidence_text(confidence),
            'source_ip': alert_data.get('source_ip', 'unknown'),
            'dest_ip': alert_data.get('dest_ip', 'unknown'),
            'summary': f"{pattern.get('description', attack_type)} detected from {alert_data.get('source_ip', 'unknown')} to {alert_data.get('dest_ip', 'unknown')}",
            'pattern': pattern.get('explanation', 'No pattern available'),
            'key_features': [],
            'top_features': [],
            'recommendations': self._get_recommendations(attack_type)
        }
        
        # Add key features from pattern
        for feature in pattern.get('key_features', [])[:top_k]:
            description = self.feature_mapper.get_description(feature)
            explanation['key_features'].append({
                'feature': feature,
                'description': description
            })
        
        # Add feature importance if provided
        if feature_importances:
            sorted_features = sorted(feature_importances.items(), key=lambda x: x[1], reverse=True)
            
            for feature, importance in sorted_features[:top_k]:
                description = self.feature_mapper.get_description(feature)
                importance_text = self.feature_mapper.get_feature_importance_text(feature, importance)
                explanation['top_features'].append({
                    'feature': feature,
                    'description': description,
                    'importance': importance,
                    'text': importance_text
                })
        
        return explanation
    
    def _get_confidence_text(self, confidence: float) -> str:
        """
        Get human-readable confidence text
        
        Args:
            confidence (float): Confidence score (0-1)
            
        Returns:
            str: Human-readable confidence text
        """
        if confidence > 0.9:
            return "Very High"
        elif confidence > 0.75:
            return "High"
        elif confidence > 0.6:
            return "Moderate"
        elif confidence > 0.4:
            return "Low"
        else:
            return "Very Low"
    
    def _get_importance_text(self, feature_importances: Dict[str, float]) -> str:
        """
        Get human-readable importance text from top features
        
        Args:
            feature_importances (Dict[str, float]): Feature importance scores
            
        Returns:
            str: Human-readable importance description
        """
        sorted_features = sorted(feature_importances.items(), key=lambda x: x[1], reverse=True)
        top_features = sorted_features[:self.max_features]
        
        parts = []
        for feature, importance in top_features:
            description = self.feature_mapper.get_description(feature)
            level = "very important" if importance > 0.5 else "moderately important"
            parts.append(f"{description} ({level})")
        
        return ", ".join(parts)
    
    def _get_recommendations(self, attack_type: str) -> List[str]:
        """
        Get recommendations for responding to an attack
        
        Args:
            attack_type (str): Type of attack
            
        Returns:
            List[str]: List of recommendations
        """
        recommendations = {
            'PortScan': [
                "Block the source IP address",
                "Review firewall rules",
                "Monitor for further scanning activity"
            ],
            'DDoS': [
                "Implement rate limiting",
                "Consider DDoS protection services",
                "Monitor bandwidth usage"
            ],
            'DoS': [
                "Block the source IP address",
                "Implement rate limiting",
                "Review firewall rules"
            ],
            'Bruteforce': [
                "Block the source IP address",
                "Implement account lockout policies",
                "Review authentication logs"
            ],
            'Botnet': [
                "Block communication with C2 servers",
                "Quarantine affected hosts",
                "Investigate for malware"
            ]
        }
        
        # Find matching recommendations
        for key, recs in recommendations.items():
            if key in attack_type or attack_type in key:
                return recs
        
        return [
            "Review the alert details",
            "Investigate the source IP",
            "Monitor for further activity"
        ]