"""
Rule definitions for the rule-based detection engine.

Each Rule describes a single detection policy: what attack it catches,
the severity to assign, and the thresholds that control when it fires.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List


@dataclass
class Rule:
    rule_id: str
    name: str
    attack_type: str
    severity: str           # low | medium | high | critical
    description: str
    enabled: bool = True
    threshold: int = 100    # event count before alerting
    time_window: int = 60   # sliding window in seconds
    cooldown: int = 60      # minimum seconds between repeated alerts for same source
    params: Dict[str, Any] = field(default_factory=dict)


def default_rules() -> List[Rule]:
    """Return the built-in rule set covering common home network intrusions."""
    return [
        Rule(
            rule_id='RULE-001',
            name='SYN Flood',
            attack_type='DoS-SYN-Flood',
            severity='high',
            description='High-rate TCP SYN packets from a single source without completing handshakes',
            threshold=100,
            time_window=10,
            cooldown=30,
        ),
        Rule(
            rule_id='RULE-002',
            name='Port Scan',
            attack_type='PortScan',
            severity='medium',
            description='Single source probing many destination ports in a short time window',
            threshold=20,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-003',
            name='ICMP Flood',
            attack_type='DoS-ICMP-Flood',
            severity='high',
            description='High-rate ICMP packets from a single source',
            threshold=50,
            time_window=5,
            cooldown=30,
        ),
        Rule(
            rule_id='RULE-004',
            name='UDP Flood',
            attack_type='DoS-UDP-Flood',
            severity='high',
            description='High-rate UDP packets from a single source',
            threshold=200,
            time_window=10,
            cooldown=30,
        ),
        Rule(
            rule_id='RULE-005',
            name='Ping Sweep',
            attack_type='Reconnaissance-PingSweep',
            severity='low',
            description='Single source sending ICMP echo requests to many different hosts',
            threshold=10,
            time_window=30,
            cooldown=120,
        ),
        Rule(
            rule_id='RULE-006',
            name='DNS Amplification',
            attack_type='DDoS-DNS-Amplification',
            severity='critical',
            description='Oversized DNS responses indicative of a DNS amplification DDoS attack',
            threshold=10,        # number of oversized responses in window
            time_window=10,
            cooldown=60,
            params={'min_response_size': 512},
        ),
        Rule(
            rule_id='RULE-007',
            name='SSH Brute Force',
            attack_type='Bruteforce-SSH',
            severity='medium',
            description='Repeated TCP SYN attempts to SSH (port 22) from a single source',
            threshold=10,
            time_window=30,
            cooldown=60,
            params={'target_port': 22},
        ),
        Rule(
            rule_id='RULE-008',
            name='FTP Brute Force',
            attack_type='Bruteforce-FTP',
            severity='medium',
            description='Repeated TCP SYN attempts to FTP (port 21) from a single source',
            threshold=10,
            time_window=30,
            cooldown=60,
            params={'target_port': 21},
        ),
        Rule(
            rule_id='RULE-009',
            name='RDP Brute Force',
            attack_type='Bruteforce-RDP',
            severity='high',
            description='Repeated TCP SYN attempts to RDP (port 3389) from a single source',
            threshold=5,
            time_window=30,
            cooldown=60,
            params={'target_port': 3389},
        ),
        Rule(
            rule_id='RULE-010',
            name='TCP NULL Scan',
            attack_type='PortScan-NullScan',
            severity='medium',
            description='TCP packets with no flags set, used to probe firewall rules stealthily',
            threshold=5,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-011',
            name='TCP XMAS Scan',
            attack_type='PortScan-XMASScan',
            severity='medium',
            description='TCP packets with FIN+PSH+URG flags, a Christmas tree scan technique',
            threshold=5,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-012',
            name='TCP FIN Scan',
            attack_type='PortScan-FINScan',
            severity='low',
            description='TCP packets with only FIN flag set, used to bypass stateless firewalls',
            threshold=5,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-013',
            name='Ping of Death',
            attack_type='DoS-PingOfDeath',
            severity='high',
            description='ICMP packets with oversized payloads exceeding safe MTU limits',
            threshold=1,
            time_window=60,
            cooldown=300,
            params={'max_safe_icmp_payload': 1472},
        ),
        Rule(
            rule_id='RULE-014',
            name='TCP SYN-FIN Scan',
            attack_type='PortScan-SYNFINScan',
            severity='medium',
            description='TCP packets with both SYN and FIN flags set, an invalid combination used to evade IDS/firewall filters',
            threshold=5,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-015',
            name='TCP ACK Scan',
            attack_type='PortScan-ACKScan',
            severity='low',
            description='Single source probing many destination ports with ACK-only packets to map firewall filtering rules',
            threshold=15,
            time_window=15,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-016',
            name='ICMP Smurf Attack',
            attack_type='DDoS-Smurf',
            severity='high',
            description='ICMP echo requests sent to a broadcast address, used to amplify traffic against a spoofed victim',
            threshold=5,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-017',
            name='ICMP Redirect Attack',
            attack_type='MITM-ICMPRedirect',
            severity='medium',
            description='ICMP redirect messages, which can be spoofed to reroute victim traffic through an attacker-controlled host',
            threshold=3,
            time_window=60,
            cooldown=300,
        ),
        Rule(
            rule_id='RULE-018',
            name='DNS Query Flood',
            attack_type='DoS-DNS-QueryFlood',
            severity='medium',
            description='Single source issuing an abnormally high rate of DNS queries, indicative of resolver abuse or DNS-based DoS',
            threshold=100,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-019',
            name='DNS ANY Query Probe',
            attack_type='Reconnaissance-DNSAnyQuery',
            severity='medium',
            description='Repeated DNS ANY-type queries, commonly used to fingerprint domains or set up amplification attacks',
            threshold=5,
            time_window=30,
            cooldown=60,
            params={'dns_qtype_any': 255},
        ),
        Rule(
            rule_id='RULE-020',
            name='MAC Address Spoofing',
            attack_type='MITM-MACSpoofing',
            severity='high',
            description='A single source MAC address associated with multiple source IP addresses in a short window, consistent with ARP/MAC spoofing',
            threshold=3,
            time_window=30,
            cooldown=120,
        ),
        Rule(
            rule_id='RULE-021',
            name='Telnet Brute Force',
            attack_type='Bruteforce-Telnet',
            severity='medium',
            description='Repeated TCP SYN attempts to Telnet (port 23) from a single source',
            threshold=10,
            time_window=30,
            cooldown=60,
            params={'target_port': 23},
        ),
        Rule(
            rule_id='RULE-022',
            name='SMB Brute Force',
            attack_type='Bruteforce-SMB',
            severity='high',
            description='Repeated TCP SYN attempts to SMB (port 445) from a single source',
            threshold=10,
            time_window=30,
            cooldown=60,
            params={'target_port': 445},
        ),
        Rule(
            rule_id='RULE-023',
            name='VNC Brute Force',
            attack_type='Bruteforce-VNC',
            severity='high',
            description='Repeated TCP SYN attempts to VNC (port 5900) from a single source',
            threshold=10,
            time_window=30,
            cooldown=60,
            params={'target_port': 5900},
        ),
        Rule(
            rule_id='RULE-024',
            name='TCP RST Flood',
            attack_type='DoS-RSTFlood',
            severity='medium',
            description='High-rate TCP RST packets from a single source, consistent with connection-reset DoS or on-path RST injection',
            threshold=100,
            time_window=10,
            cooldown=30,
        ),
        Rule(
            rule_id='RULE-025',
            name='IP Fragmentation Flood',
            attack_type='DoS-IPFragmentation',
            severity='medium',
            description='High rate of fragmented IP packets from a single source, used for firewall/IDS evasion or fragmentation-based (teardrop-style) DoS',
            threshold=50,
            time_window=10,
            cooldown=30,
        ),
        Rule(
            rule_id='RULE-026',
            name='TCP Zero-Window DoS',
            attack_type='DoS-TCPZeroWindow',
            severity='medium',
            description='Repeated TCP packets advertising a zero receive window from a single source, consistent with a Sockstress-style resource-exhaustion attack',
            threshold=20,
            time_window=15,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-027',
            name='DNS Tunneling',
            attack_type='Exfiltration-DNSTunneling',
            severity='high',
            description='Repeated DNS queries with abnormally long query names, indicative of DNS tunneling used for data exfiltration or covert C2',
            threshold=5,
            time_window=30,
            cooldown=120,
            params={'max_qname_length': 50},
        ),
        Rule(
            rule_id='RULE-028',
            name='Malformed Packet Flood',
            attack_type='Evasion-MalformedPackets',
            severity='low',
            description='High rate of malformed or unparseable packets from a single source, potentially protocol fuzzing or IDS-evasion probing',
            threshold=30,
            time_window=10,
            cooldown=60,
        ),
        Rule(
            rule_id='RULE-029',
            name='ICMP Timestamp Probe',
            attack_type='Reconnaissance-ICMPTimestamp',
            severity='low',
            description='ICMP timestamp request probes used for OS fingerprinting and host-discovery reconnaissance',
            threshold=5,
            time_window=20,
            cooldown=120,
        ),
        Rule(
            rule_id='RULE-030',
            name='ICMP Destination Unreachable Flood',
            attack_type='DoS-ICMPUnreachableFlood',
            severity='medium',
            description='High-rate ICMP destination-unreachable messages from a single source, consistent with DoS backscatter from a spoofed attack or aggressive network mapping',
            threshold=50,
            time_window=10,
            cooldown=30,
        ),
    ]
